alias ctagsp='ctags . ${VIRTUAL_ENV:-$CONDA_PREFIX}/lib/python*/site-packages'
alias largest='du -hsx * | sort -rh | head -15'
alias ls='ls --color=auto'
alias repos='tmux new-session -A -c ~/repos -s repos'
alias rgi='rg --ignore-vcs'
