require('dietrichm.lsp')
require('dietrichm.completion')
require('dietrichm.treesitter')
require('dietrichm.formatters')
require('dietrichm.telescope')
require('dietrichm.gitsigns')
require('dietrichm.fs')
