-- Remove `$` from iskeyword set by pangloss/vim-javascript.
vim.opt_local.iskeyword:remove('$')

local phpHighlights = {
  'phpBackslashDoubleQuote',
  'phpBackslashSequences',
  'phpBackslashSingleQuote',
  'phpBacktick',
  'phpBaselib',
  'phpBinaryError',
  'phpBoolean',
  'phpBrackets',
  'phpComment',
  'phpConditional',
  'phpConstant',
  'phpCoreConstant',
  'phpDefine',
  'phpDocCustomTags',
  'phpDocTags',
  'phpDocTodo',
  'phpEnvVar',
  'phpException',
  'phpFCKeyword',
  'phpFloat',
  'phpFloatError',
  'phpFunctions',
  'phpIdentifier',
  'phpIdentifierConst',
  'phpIdentifierSimply',
  'phpInclude',
  'phpIntVar',
  'phpInterpBogusDollarCurley',
  'phpInterpDollarCurly1',
  'phpInterpDollarCurly2',
  'phpInterpSimpleBracketsInner',
  'phpInterpSimpleCurly',
  'phpInterpSimpleError',
  'phpInterpVarname',
  'phpKeyword',
  'phpLabel',
  'phpMemberSelector',
  'phpMethods',
  'phpNumber',
  'phpOctalError',
  'phpOperator',
  'phpParent',
  'phpParentError',
  'phpRelation',
  'phpRepeat',
  'phpSCKeyword',
  'phpStatement',
  'phpStorageClass',
  'phpStringDouble',
  'phpStringSingle',
  'phpStructure',
  'phpTodo',
  'phpType',
  'phpVarSelector',
}

-- Clear legacy PHP highlight groups in favour of treesitter.
for _, phpHighlight in ipairs(phpHighlights) do
  vim.cmd.highlight { 'link', phpHighlight, 'NONE' }
end
