local map = vim.keymap.set

map('i', '<C-;>', [[<C-O>:call searchpair('(', '', ')')<CR><Right>]])
map('i', '<S-Tab>', '<Right>')
map('n', '#', [[:setlocal hlsearch | :normal! #<CR>]])
map('n', '*', [[:setlocal hlsearch | :normal! *<CR>]])
map('n', '<Leader>da', [[:%bd<CR>]])
map('n', '<Leader>m', [[:make %<CR>]])
map('n', '<Leader>M', [[:make<CR>]])
map('n', '<Leader>pc', [[:let @+ = expand('%:.') | :echomsg "Copied:" @+<CR>]], { silent = true })
map('n', '<Leader>Pc', [[:let @+ = expand('%:p:~') | :echomsg "Copied:" @+<CR>]], { silent = true })
map('n', '<Leader>q', vim.diagnostic.setloclist)
map('n', '<Leader>rc', [[:noautocmd update | :TestFile<CR>]])
map('n', '<Leader>rr', [[:noautocmd update | :TestLast<CR>]])
map('n', '<Leader>rt', [[:noautocmd update | :TestNearest<CR>]])
map('n', '<Space>', '')
map('n', '\\', [[:setlocal hlsearch!<CR>]])
map('n', 'g#', [[:setlocal hlsearch | :normal! g#<CR>]])
map('n', 'g*', [[:setlocal hlsearch | :normal! g*<CR>]])
map('n', 'j', [[v:count == 0 && &ft != 'qf' ? 'gj' : 'j']], { expr = true })
map('n', 'k', [[v:count == 0 && &ft != 'qf' ? 'gk' : 'k']], { expr = true })
map('n', '{', [[:keepjumps normal! {<CR>]], { silent = true })
map('n', '}', [[:keepjumps normal! }<CR>]], { silent = true })
map('t', '<Esc>', [[<C-\><C-n>]])
