alias ctagsp='ctags . ${VIRTUAL_ENV:-$CONDA_PREFIX}/lib/python*/site-packages'
alias info='info --vi-keys'
alias largest='du -hsx * | sort -rh | head -15'
alias ls='ls --color=auto'
alias rgi='rg --ignore-vcs'
alias rgiw='rg --ignore-vcs  --word-regexp'
alias rgw='rg  --word-regexp'
