name: Lua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Lua
      uses: lewis6991/gh-actions-lua@master
    - name: Set up Luarocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Install Luacheck
      run: |
        luarocks install luacheck
    - name: Install StyLua
      run: |
        wget -q https://github.com/JohnnyMorganz/StyLua/releases/download/v2.1.0/stylua-linux-x86_64.zip
        unzip stylua-linux-x86_64.zip
        chmod u+x stylua
    - name: Lint Lua files
      run: |
        PATH="$PATH:." make lint
