name: Lua

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Lua
      uses: leafo/gh-actions-lua@v12
    - name: Set up Luarocks
      uses: leafo/gh-actions-luarocks@v6
    - name: Install Luacheck
      run: luarocks install luacheck
    - name: Install StyLua
      run: |
        wget -q https://github.com/JohnnyMorganz/StyLua/releases/download/v2.4.0/stylua-linux-x86_64.zip
        unzip stylua-linux-x86_64.zip
        chmod u+x stylua
    - name: Lint Lua files
      run: PATH="$PATH:." make lint
