name: VimL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --pre vim-vint
    - name: Lint with Vint
      run: |
        make lint
